apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chainsaw-app-service.fullname" . }}
  labels:
    {{- include "chainsaw-app-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chainsaw-app-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chainsaw-app-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chainsaw-app-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              {{- toYaml .Values.livenessProbe.httpGet | nindent 16 }}
            initialDelaySeconds: 60
            periodSeconds: 120
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              {{- toYaml .Values.readinessProbe.httpGet | nindent 16 }}
            initialDelaySeconds: 60
            periodSeconds: 120
            timeoutSeconds: 5
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
